name: Build & Deploy (Production)

on:
  push:
    branches:
      - master
    paths:
      - 'packages/server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.15.0

      - name: Deploy
        run: echo "Deployed"
